# -- coding: utf-8 --

# Form implementation generated from reading ui file 'registro.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(451, 333)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 50, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 170, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 210, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.btn_registrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_registrar.setGeometry(QtCore.QRect(250, 260, 75, 23))
        self.btn_registrar.setObjectName("btn_registrar")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(130, 210, 191, 22))
        self.comboBox.setObjectName("comboBox")
        self.plainTextEdit_Nombre = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_Nombre.setGeometry(QtCore.QRect(130, 50, 191, 21))
        self.plainTextEdit_Nombre.setObjectName("plainTextEdit_Nombre")
        self.plainTextEdit_Apellidos = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_Apellidos.setGeometry(QtCore.QRect(130, 170, 191, 21))
        self.plainTextEdit_Apellidos.setObjectName("plainTextEdit_Apellidos")
        self.plainTextEdit_Usuario = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_Usuario.setGeometry(QtCore.QRect(130, 130, 191, 21))
        self.plainTextEdit_Usuario.setObjectName("plainTextEdit_Usuario")
        self.plainTextEdit_Contrasena = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_Contrasena.setGeometry(QtCore.QRect(130, 90, 191, 21))
        self.plainTextEdit_Contrasena.setObjectName("plainTextEdit_Contrasena")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(330, 50, 111, 231))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 451, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Nombre"))
        self.label_2.setText(_translate("MainWindow", "Apellidos"))
        self.label_3.setText(_translate("MainWindow", "Usuario"))
        self.label_4.setText(_translate("MainWindow", "Contraseña"))
        self.label_5.setText(_translate("MainWindow", "Rol"))
        self.btn_registrar.setText(_translate("MainWindow", "Registrar"))
