# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'webScraper.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.panelEstadistica = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.panelEstadistica.sizePolicy().hasHeightForWidth())
        self.panelEstadistica.setSizePolicy(sizePolicy)
        self.panelEstadistica.setAutoFillBackground(False)
        self.panelEstadistica.setObjectName("panelEstadistica")
        self.gridLayout.addWidget(self.panelEstadistica, 0, 1, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 1, 1, 1)
        self.btn_atras = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_atras.sizePolicy().hasHeightForWidth())
        self.btn_atras.setSizePolicy(sizePolicy)
        self.btn_atras.setAutoFillBackground(False)
        self.btn_atras.setObjectName("btn_atras")
        self.gridLayout_4.addWidget(self.btn_atras, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 3, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_reintentar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reintentar.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_reintentar.sizePolicy().hasHeightForWidth())
        self.btn_reintentar.setSizePolicy(sizePolicy)
        self.btn_reintentar.setObjectName("btn_reintentar")
        self.gridLayout_3.addWidget(self.btn_reintentar, 0, 1, 1, 1)
        self.btn_obtener = QtWidgets.QPushButton(self.centralwidget)
        self.btn_obtener.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_obtener.sizePolicy().hasHeightForWidth())
        self.btn_obtener.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btn_obtener.setFont(font)
        self.btn_obtener.setAutoFillBackground(False)
        self.btn_obtener.setObjectName("btn_obtener")
        self.gridLayout_3.addWidget(self.btn_obtener, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 3, 1, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_2)
        self.comboBox_paginas = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_paginas.setEnabled(True)
        self.comboBox_paginas.setObjectName("comboBox_paginas")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_paginas)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_4.addWidget(self.lineEdit_2)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.gridLayout_5.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.maximo_text = QtWidgets.QLabel(self.centralwidget)
        self.maximo_text.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.maximo_text.setFont(font)
        self.maximo_text.setObjectName("maximo_text")
        self.gridLayout_5.addWidget(self.maximo_text, 1, 0, 1, 1)
        self.checkBox_opiniones = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_opiniones.setChecked(True)
        self.checkBox_opiniones.setObjectName("checkBox_opiniones")
        self.gridLayout_5.addWidget(self.checkBox_opiniones, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 3, 0, 1, 1)
        self.formLayout.setLayout(7, QtWidgets.QFormLayout.FieldRole, self.gridLayout_5)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.FieldRole, spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(6, QtWidgets.QFormLayout.FieldRole, spacerItem6)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WebScraper"))
        self.btn_atras.setText(_translate("MainWindow", "Atrás"))
        self.btn_reintentar.setText(_translate("MainWindow", "REINTENTAR"))
        self.btn_obtener.setText(_translate("MainWindow", "OBTENER"))
        self.label_2.setText(_translate("MainWindow", "Seleccione una página para obtener opiniones:"))
        self.comboBox_paginas.setItemText(0, _translate("MainWindow", "booking"))
        self.comboBox_paginas.setItemText(1, _translate("MainWindow", "opcion2"))
        self.comboBox_paginas.setItemText(2, _translate("MainWindow", "opcion3"))
        self.label.setText(_translate("MainWindow", "URL:"))
        self.maximo_text.setText(_translate("MainWindow", "Seleccione el máximo de opiniones que desa visualizar:"))
        self.checkBox_opiniones.setText(_translate("MainWindow", "Mostrar todas las opiniones"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

